version: '3'

volumes:
  mongo-volume:

services:
  mongo:
    image: mongo
    container_name: mongodb
    restart: always
    ports:
      - '27017-27019:27017-27019'
    volumes:
      - mongo-volume:/data/db
      - ./docker/db:/docker-entrypoint-initdb.d
    environment:
      MONGO_INITDB_DATABASE: ${DB_DATABASE}
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: pass
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}

  redis:
    image: redis
    container_name: redis
    restart: always
    ports:
      - '6379:6379'
